port: 8080
rabbitmq_url: "amqp://guest:guest@localhost:5672/"
rabbitmq_transfer_money_queue_name: "transfer_money_queue"
rabbitmq_transfer_money_exchange_name: "transfer_money_exchange"
rabbitmq_transfer_money_exchange_type: "direct"

couchbase_username: "Administrator"
couchbase_password: "123456789"
couchbase_url: "couchbase://localhost"